// ==========================================================================
// produtos.js
// Base de dados dos produtos do Cardápio Digital
// Categorias: ENTRADAS, PRATO PRINCIPAL, SOBREMESAS, BEBIDAS, CARTA DE VINHOS
// Total: 150 produtos (30 por categoria), cada um com descrição própria
// ==========================================================================

const produtos = [
    { id: "ent001", nome: "Bruschetta Italiana", descricao: "Fatias de pão italiano tostado cobertas com tomate fresco, manjericão e azeite extravirgem.", preco: 33.67, categoria: "ENTRADAS" },
    { id: "ent002", nome: "Bolinho de Bacalhau", descricao: "Bolinhos crocantes por fora e macios por dentro, feitos com bacalhau desfiado e batata.", preco: 18.6, categoria: "ENTRADAS" },
    { id: "ent003", nome: "Carpaccio de Carne", descricao: "Finas lâminas de carne crua temperadas com azeite, alcaparras e lascas de parmesão.", preco: 24.6, categoria: "ENTRADAS" },
    { id: "ent004", nome: "Camarão à Milanesa", descricao: "Camarões empanados e fritos até dourar, servidos com molho tártaro.", preco: 23.36, categoria: "ENTRADAS" },
    { id: "ent005", nome: "Coxinha de Frango", descricao: "Massa macia recheada com frango desfiado cremoso, empanada e frita na hora.", preco: 35.68, categoria: "ENTRADAS" },
    { id: "ent006", nome: "Casquinha de Siri", descricao: "Carne de siri refogada com temperos, gratinada na própria casca.", preco: 34.24, categoria: "ENTRADAS" },
    { id: "ent007", nome: "Salada Caprese", descricao: "Rodelas de tomate e mussarela de búfala intercaladas com manjericão fresco e azeite.", preco: 39.41, categoria: "ENTRADAS" },
    { id: "ent008", nome: "Pão de Alho", descricao: "Pão artesanal recheado com manteiga de alho e ervas, assado até ficar crocante.", preco: 20.09, categoria: "ENTRADAS" },
    { id: "ent009", nome: "Polenta Frita", descricao: "Bastões de polenta crocantes por fora e cremosos por dentro, acompanhados de molho de ervas.", preco: 28.13, categoria: "ENTRADAS" },
    { id: "ent010", nome: "Ceviche de Peixe", descricao: "Cubos de peixe branco marinados em limão, cebola roxa, coentro e pimenta.", preco: 18.72, categoria: "ENTRADAS" },
    { id: "ent011", nome: "Empanada Argentina", descricao: "Massa folhada recheada com carne moída, cebola e temperos, assada até dourar.", preco: 23.25, categoria: "ENTRADAS" },
    { id: "ent012", nome: "Croquete de Carne", descricao: "Croquetes crocantes recheados com carne bovina desfiada e temperos especiais.", preco: 30.13, categoria: "ENTRADAS" },
    { id: "ent013", nome: "Dadinho de Tapioca", descricao: "Cubinhos de tapioca com queijo coalho, fritos e servidos com geleia de pimenta.", preco: 18.64, categoria: "ENTRADAS" },
    { id: "ent014", nome: "Falafel", descricao: "Bolinhos de grão-de-bico temperados com especiarias árabes, fritos e crocantes.", preco: 22.77, categoria: "ENTRADAS" },
    { id: "ent015", nome: "Hummus com Pita", descricao: "Pasta cremosa de grão-de-bico e tahine, servida com pão pita quentinho.", preco: 33.6, categoria: "ENTRADAS" },
    { id: "ent016", nome: "Isca de Frango", descricao: "Tiras de peito de frango empanadas e fritas, servidas com molho barbecue.", preco: 31.08, categoria: "ENTRADAS" },
    { id: "ent017", nome: "Kibe Frito", descricao: "Massa de trigo com carne moída e hortelã, frita até ficar crocante por fora.", preco: 23.29, categoria: "ENTRADAS" },
    { id: "ent018", nome: "Mandioca Frita", descricao: "Pedaços de mandioca fritos até ficarem dourados e crocantes, com toque de sal grosso.", preco: 32.14, categoria: "ENTRADAS" },
    { id: "ent019", nome: "Pastel de Queijo", descricao: "Massa fina e crocante recheada com queijo derretido, frita na hora do pedido.", preco: 37.43, categoria: "ENTRADAS" },
    { id: "ent020", nome: "Queijo Coalho Grelhado", descricao: "Espetos de queijo coalho grelhados, servidos com melado de cana.", preco: 18.16, categoria: "ENTRADAS" },
    { id: "ent021", nome: "Rolinho Primavera", descricao: "Rolinhos crocantes recheados com legumes salteados, ao estilo oriental.", preco: 37.34, categoria: "ENTRADAS" },
    { id: "ent022", nome: "Salpicão de Frango", descricao: "Salada cremosa de frango desfiado com legumes e maionese temperada.", preco: 34.76, categoria: "ENTRADAS" },
    { id: "ent023", nome: "Tábua de Frios", descricao: "Seleção de queijos e embutidos nobres, acompanhada de torradas e geleias.", preco: 26.17, categoria: "ENTRADAS" },
    { id: "ent024", nome: "Torresmo Crocante", descricao: "Cubos de torresmo crocante, temperados com alho e sal grosso.", preco: 21.73, categoria: "ENTRADAS" },
    { id: "ent025", nome: "Vinagrete de Polvo", descricao: "Polvo cozido no ponto certo, marinado em vinagrete de ervas frescas.", preco: 40.97, categoria: "ENTRADAS" },
    { id: "ent026", nome: "Anéis de Cebola", descricao: "Anéis de cebola empanados em farinha temperada e fritos até dourar.", preco: 26.08, categoria: "ENTRADAS" },
    { id: "ent027", nome: "Batata Rústica", descricao: "Batatas assadas com casca, temperadas com alecrim e páprica defumada.", preco: 20.23, categoria: "ENTRADAS" },
    { id: "ent028", nome: "Canapé de Salmão", descricao: "Torradinhas cobertas com salmão defumado, cream cheese e endro.", preco: 20.32, categoria: "ENTRADAS" },
    { id: "ent029", nome: "Espetinho de Frango", descricao: "Cubos de frango marinados e grelhados no espeto, servidos com molho especial.", preco: 38.34, categoria: "ENTRADAS" },
    { id: "ent030", nome: "Guacamole com Nachos", descricao: "Abacate amassado com limão, tomate e cebola, acompanhado de nachos crocantes.", preco: 32.49, categoria: "ENTRADAS" },
    { id: "pri001", nome: "Filé Mignon ao Molho Madeira", descricao: "Medalhão de filé mignon grelhado, coberto com molho madeira encorpado.", preco: 79.36, categoria: "PRATO PRINCIPAL" },
    { id: "pri002", nome: "Frango Grelhado com Ervas", descricao: "Peito de frango grelhado, temperado com ervas finas e azeite.", preco: 75.49, categoria: "PRATO PRINCIPAL" },
    { id: "pri003", nome: "Salmão Grelhado", descricao: "Filé de salmão grelhado no ponto, servido com legumes salteados.", preco: 65.81, categoria: "PRATO PRINCIPAL" },
    { id: "pri004", nome: "Picanha na Chapa", descricao: "Fatias de picanha grelhadas na chapa, servidas com arroz e farofa.", preco: 87.66, categoria: "PRATO PRINCIPAL" },
    { id: "pri005", nome: "Lasanha à Bolonhesa", descricao: "Camadas de massa, molho bolonhesa e queijo gratinado no forno.", preco: 57.93, categoria: "PRATO PRINCIPAL" },
    { id: "pri006", nome: "Risoto de Camarão", descricao: "Arroz arbóreo cremoso cozido lentamente com camarões e toque de limão siciliano.", preco: 66.6, categoria: "PRATO PRINCIPAL" },
    { id: "pri007", nome: "Feijoada Completa", descricao: "Feijão preto cozido com carnes selecionadas, acompanhado de arroz, couve e laranja.", preco: 80.47, categoria: "PRATO PRINCIPAL" },
    { id: "pri008", nome: "Bife à Parmegiana", descricao: "Bife empanado coberto com molho de tomate e queijo derretido, gratinado.", preco: 69.93, categoria: "PRATO PRINCIPAL" },
    { id: "pri009", nome: "Costela ao Vinho Tinto", descricao: "Costela bovina cozida lentamente em molho de vinho tinto até desmanchar.", preco: 82.09, categoria: "PRATO PRINCIPAL" },
    { id: "pri010", nome: "Peixe Assado com Legumes", descricao: "Filé de peixe assado com mix de legumes coloridos e ervas frescas.", preco: 67.87, categoria: "PRATO PRINCIPAL" },
    { id: "pri011", nome: "Strogonoff de Frango", descricao: "Cubos de frango em molho cremoso com champignon, servido com arroz e batata palha.", preco: 74.23, categoria: "PRATO PRINCIPAL" },
    { id: "pri012", nome: "Strogonoff de Carne", descricao: "Tiras de carne bovina em molho cremoso de tomate e champignon.", preco: 41.29, categoria: "PRATO PRINCIPAL" },
    { id: "pri013", nome: "Moqueca de Peixe", descricao: "Peixe cozido em leite de coco, dendê, pimentões e coentro, ao estilo baiano.", preco: 50.39, categoria: "PRATO PRINCIPAL" },
    { id: "pri014", nome: "Penne ao Molho Branco", descricao: "Massa penne al dente ao molho branco cremoso com toque de noz-moscada.", preco: 53.47, categoria: "PRATO PRINCIPAL" },
    { id: "pri015", nome: "Espaguete à Carbonara", descricao: "Espaguete envolto em molho cremoso de ovos, queijo e bacon crocante.", preco: 42.99, categoria: "PRATO PRINCIPAL" },
    { id: "pri016", nome: "Frango à Parmegiana", descricao: "Filé de frango empanado, coberto com molho de tomate e queijo gratinado.", preco: 50.64, categoria: "PRATO PRINCIPAL" },
    { id: "pri017", nome: "Escondidinho de Carne Seca", descricao: "Purê de mandioca gratinado sobre carne seca desfiada e refogada.", preco: 44.05, categoria: "PRATO PRINCIPAL" },
    { id: "pri018", nome: "Arroz de Polvo", descricao: "Arroz cozido no caldo de polvo, finalizado com pedaços do próprio polvo.", preco: 52.9, categoria: "PRATO PRINCIPAL" },
    { id: "pri019", nome: "Paella Marinera", descricao: "Arroz espanhol cozido com frutos do mar variados e açafrão.", preco: 70.78, categoria: "PRATO PRINCIPAL" },
    { id: "pri020", nome: "Contra-Filé Grelhado", descricao: "Contra-filé suculento grelhado no ponto, servido com molho de ervas.", preco: 57.24, categoria: "PRATO PRINCIPAL" },
    { id: "pri021", nome: "Cordeiro Assado", descricao: "Pernil de cordeiro assado lentamente com alecrim e alho.", preco: 57.51, categoria: "PRATO PRINCIPAL" },
    { id: "pri022", nome: "Camarão na Moranga", descricao: "Camarões ao creme servidos dentro de uma moranga assada.", preco: 49.48, categoria: "PRATO PRINCIPAL" },
    { id: "pri023", nome: "Bacalhau à Portuguesa", descricao: "Lascas de bacalhau assadas com batatas, cebola, azeitonas e azeite.", preco: 52.35, categoria: "PRATO PRINCIPAL" },
    { id: "pri024", nome: "Tilápia Grelhada", descricao: "Filé de tilápia grelhado, temperado com limão e ervas frescas.", preco: 85.83, categoria: "PRATO PRINCIPAL" },
    { id: "pri025", nome: "Risoto de Costela", descricao: "Arroz cremoso finalizado com costela bovina desfiada e queijo parmesão.", preco: 71.4, categoria: "PRATO PRINCIPAL" },
    { id: "pri026", nome: "Fettuccine ao Molho Pesto", descricao: "Massa fettuccine ao molho pesto de manjericão fresco e castanhas.", preco: 69.46, categoria: "PRATO PRINCIPAL" },
    { id: "pri027", nome: "Nhoque ao Sugo", descricao: "Nhoque de batata macio ao molho de tomate caseiro e manjericão.", preco: 47.56, categoria: "PRATO PRINCIPAL" },
    { id: "pri028", nome: "Yakisoba de Carne", descricao: "Macarrão oriental salteado com carne e legumes crocantes ao molho shoyu.", preco: 75.46, categoria: "PRATO PRINCIPAL" },
    { id: "pri029", nome: "Panqueca de Frango", descricao: "Panqueca recheada com frango desfiado, coberta com molho de tomate e queijo.", preco: 47.17, categoria: "PRATO PRINCIPAL" },
    { id: "pri030", nome: "Kafta com Arroz Árabe", descricao: "Espetos de carne moída temperada, servidos com arroz árabe e molho de tahine.", preco: 57.97, categoria: "PRATO PRINCIPAL" },
    { id: "sob001", nome: "Petit Gateau", descricao: "Bolinho de chocolate quente com centro derretido, acompanhado de sorvete de creme.", preco: 31.81, categoria: "SOBREMESAS" },
    { id: "sob002", nome: "Pudim de Leite", descricao: "Pudim tradicional de leite condensado com calda de caramelo.", preco: 25.52, categoria: "SOBREMESAS" },
    { id: "sob003", nome: "Mousse de Chocolate", descricao: "Mousse aerada de chocolate meio amargo, leve e cremosa.", preco: 24.03, categoria: "SOBREMESAS" },
    { id: "sob004", nome: "Torta de Limão", descricao: "Base crocante com creme de limão e cobertura de merengue maçaricado.", preco: 26.32, categoria: "SOBREMESAS" },
    { id: "sob005", nome: "Brownie com Sorvete", descricao: "Brownie de chocolate quentinho servido com bola de sorvete de creme.", preco: 29.17, categoria: "SOBREMESAS" },
    { id: "sob006", nome: "Cheesecake de Frutas Vermelhas", descricao: "Cheesecake cremoso com calda artesanal de frutas vermelhas.", preco: 27.97, categoria: "SOBREMESAS" },
    { id: "sob007", nome: "Sorvete Artesanal", descricao: "Duas bolas de sorvete artesanal, sabor à escolha do cliente.", preco: 18.12, categoria: "SOBREMESAS" },
    { id: "sob008", nome: "Tiramisù", descricao: "Camadas de biscoito champagne embebido em café, com creme mascarpone.", preco: 14.58, categoria: "SOBREMESAS" },
    { id: "sob009", nome: "Pavê de Chocolate", descricao: "Camadas de biscoito, creme de chocolate e chantilly geladinho.", preco: 19.68, categoria: "SOBREMESAS" },
    { id: "sob010", nome: "Torta Holandesa", descricao: "Torta gelada com camadas de biscoito, sorvete e cobertura de chocolate.", preco: 18.82, categoria: "SOBREMESAS" },
    { id: "sob011", nome: "Quindim", descricao: "Doce tradicional feito com gemas, açúcar e coco, assado em banho-maria.", preco: 17.8, categoria: "SOBREMESAS" },
    { id: "sob012", nome: "Bolo de Cenoura com Chocolate", descricao: "Bolo fofinho de cenoura coberto com generosa calda de chocolate.", preco: 30.97, categoria: "SOBREMESAS" },
    { id: "sob013", nome: "Banana Flambada", descricao: "Banana caramelizada e flambada, servida com sorvete de creme.", preco: 29.77, categoria: "SOBREMESAS" },
    { id: "sob014", nome: "Creme Brûlée", descricao: "Creme de baunilha com casquinha de açúcar caramelizado crocante.", preco: 19.66, categoria: "SOBREMESAS" },
    { id: "sob015", nome: "Torta de Maçã", descricao: "Torta amanteigada recheada com maçãs caramelizadas e canela.", preco: 25.8, categoria: "SOBREMESAS" },
    { id: "sob016", nome: "Mil Folhas", descricao: "Camadas de massa folhada crocante intercaladas com creme de confeiteiro.", preco: 21.12, categoria: "SOBREMESAS" },
    { id: "sob017", nome: "Doce de Leite com Nozes", descricao: "Doce de leite cremoso finalizado com nozes crocantes.", preco: 30.46, categoria: "SOBREMESAS" },
    { id: "sob018", nome: "Salada de Frutas", descricao: "Mix de frutas frescas da estação, servido gelado.", preco: 22.26, categoria: "SOBREMESAS" },
    { id: "sob019", nome: "Sorvete de Creme com Calda", descricao: "Bolas de sorvete de creme cobertas com calda quente à escolha.", preco: 18.77, categoria: "SOBREMESAS" },
    { id: "sob020", nome: "Torta de Chocolate Belga", descricao: "Torta densa de chocolate belga com cobertura brilhante.", preco: 18.44, categoria: "SOBREMESAS" },
    { id: "sob021", nome: "Romeu e Julieta", descricao: "Fatia de queijo minas fresco acompanhada de goiabada cremosa.", preco: 24.1, categoria: "SOBREMESAS" },
    { id: "sob022", nome: "Cocada Cremosa", descricao: "Doce cremoso de coco ralado cozido lentamente no ponto certo.", preco: 18.73, categoria: "SOBREMESAS" },
    { id: "sob023", nome: "Bolo de Rolo", descricao: "Bolo fino enrolado, recheado com goiabada, tradicional de Pernambuco.", preco: 24.52, categoria: "SOBREMESAS" },
    { id: "sob024", nome: "Manjar Branco", descricao: "Pudim de leite de coco com calda de ameixa, refrescante e leve.", preco: 30.16, categoria: "SOBREMESAS" },
    { id: "sob025", nome: "Torta de Nozes", descricao: "Torta amanteigada recheada com creme e nozes crocantes.", preco: 21.19, categoria: "SOBREMESAS" },
    { id: "sob026", nome: "Suspiro Recheado", descricao: "Suspiro crocante recheado com doce de leite e chantilly.", preco: 17.95, categoria: "SOBREMESAS" },
    { id: "sob027", nome: "Mousse de Maracujá", descricao: "Mousse azedinha de maracujá, leve e refrescante.", preco: 31.96, categoria: "SOBREMESAS" },
    { id: "sob028", nome: "Beijinho Gourmet", descricao: "Docinho de coco com leite condensado, finalizado com cravo.", preco: 23.17, categoria: "SOBREMESAS" },
    { id: "sob029", nome: "Brigadeiro Gourmet", descricao: "Brigadeiro artesanal de chocolate belga com granulado crocante.", preco: 15.64, categoria: "SOBREMESAS" },
    { id: "sob030", nome: "Sagu com Creme", descricao: "Sagu cozido no vinho tinto, servido com creme de baunilha.", preco: 14.85, categoria: "SOBREMESAS" },
    { id: "beb001", nome: "Água Mineral", descricao: "Água mineral sem gás, servida bem gelada.", preco: 8.41, categoria: "BEBIDAS" },
    { id: "beb002", nome: "Água com Gás", descricao: "Água mineral gaseificada, refrescante e leve.", preco: 19.8, categoria: "BEBIDAS" },
    { id: "beb003", nome: "Refrigerante Cola", descricao: "Refrigerante sabor cola gelado, lata de 350ml.", preco: 23.43, categoria: "BEBIDAS" },
    { id: "beb004", nome: "Refrigerante Guaraná", descricao: "Refrigerante sabor guaraná bem geladinho, lata de 350ml.", preco: 15.29, categoria: "BEBIDAS" },
    { id: "beb005", nome: "Suco de Laranja", descricao: "Suco natural de laranja, extraído na hora.", preco: 7.4, categoria: "BEBIDAS" },
    { id: "beb006", nome: "Suco de Abacaxi", descricao: "Suco natural de abacaxi com hortelã, bem gelado.", preco: 14.4, categoria: "BEBIDAS" },
    { id: "beb007", nome: "Suco de Maracujá", descricao: "Suco natural de maracujá, equilíbrio entre doce e azedo.", preco: 27.91, categoria: "BEBIDAS" },
    { id: "beb008", nome: "Suco de Uva", descricao: "Suco natural de uva integral, servido gelado.", preco: 17.64, categoria: "BEBIDAS" },
    { id: "beb009", nome: "Limonada Suíça", descricao: "Limonada batida com leite condensado, cremosa e refrescante.", preco: 27.36, categoria: "BEBIDAS" },
    { id: "beb010", nome: "Chá Gelado", descricao: "Chá preto gelado, levemente adoçado e servido com gelo.", preco: 24.94, categoria: "BEBIDAS" },
    { id: "beb011", nome: "Café Expresso", descricao: "Café expresso tradicional, encorpado e aromático.", preco: 6.25, categoria: "BEBIDAS" },
    { id: "beb012", nome: "Cappuccino", descricao: "Café expresso com leite vaporizado e espuma cremosa.", preco: 21.86, categoria: "BEBIDAS" },
    { id: "beb013", nome: "Chocolate Quente", descricao: "Chocolate quente cremoso, feito com chocolate meio amargo.", preco: 21.0, categoria: "BEBIDAS" },
    { id: "beb014", nome: "Água de Coco", descricao: "Água de coco natural, gelada, servida no copo.", preco: 17.81, categoria: "BEBIDAS" },
    { id: "beb015", nome: "Suco de Melancia", descricao: "Suco natural de melancia, leve e refrescante.", preco: 11.87, categoria: "BEBIDAS" },
    { id: "beb016", nome: "Suco Verde Detox", descricao: "Suco à base de couve, maçã e gengibre, energizante.", preco: 20.1, categoria: "BEBIDAS" },
    { id: "beb017", nome: "Refrigerante Zero Açúcar", descricao: "Refrigerante sabor cola sem açúcar, lata de 350ml.", preco: 8.45, categoria: "BEBIDAS" },
    { id: "beb018", nome: "Energético", descricao: "Bebida energética gelada, lata de 250ml.", preco: 15.56, categoria: "BEBIDAS" },
    { id: "beb019", nome: "Milkshake de Chocolate", descricao: "Milkshake cremoso de sorvete de chocolate batido com leite.", preco: 15.98, categoria: "BEBIDAS" },
    { id: "beb020", nome: "Milkshake de Morango", descricao: "Milkshake cremoso de sorvete de morango batido com leite.", preco: 26.98, categoria: "BEBIDAS" },
    { id: "beb021", nome: "Vitamina de Frutas", descricao: "Vitamina batida com frutas frescas da estação e leite.", preco: 25.27, categoria: "BEBIDAS" },
    { id: "beb022", nome: "Chá Gelado de Pêssego", descricao: "Chá gelado com sabor de pêssego, doce e refrescante.", preco: 11.79, categoria: "BEBIDAS" },
    { id: "beb023", nome: "Cerveja Pilsen", descricao: "Cerveja pilsen gelada, leve e refrescante, garrafa 600ml.", preco: 17.01, categoria: "BEBIDAS" },
    { id: "beb024", nome: "Cerveja Artesanal IPA", descricao: "Cerveja artesanal estilo IPA, aromática e amargor equilibrado.", preco: 9.93, categoria: "BEBIDAS" },
    { id: "beb025", nome: "Caipirinha", descricao: "Cachaça, limão, açúcar e gelo, o clássico drink brasileiro.", preco: 26.08, categoria: "BEBIDAS" },
    { id: "beb026", nome: "Caipiroska", descricao: "Vodka, limão, açúcar e gelo, versão da caipirinha com vodka.", preco: 25.15, categoria: "BEBIDAS" },
    { id: "beb027", nome: "Mojito", descricao: "Rum, hortelã, limão e água com gás, drink cubano refrescante.", preco: 12.57, categoria: "BEBIDAS" },
    { id: "beb028", nome: "Gin Tônica", descricao: "Gin premium com água tônica, servido com rodelas de limão.", preco: 20.06, categoria: "BEBIDAS" },
    { id: "beb029", nome: "Refrigerante Limão", descricao: "Refrigerante sabor limão gelado, lata de 350ml.", preco: 19.4, categoria: "BEBIDAS" },
    { id: "beb030", nome: "Água Tônica", descricao: "Água tônica gelada, ideal para compor drinks.", preco: 9.36, categoria: "BEBIDAS" },
    { id: "vin001", nome: "Vinho Tinto Cabernet Sauvignon", descricao: "Vinho tinto encorpado, com notas de frutas escuras e taninos marcantes.", preco: 178.44, categoria: "CARTA DE VINHOS" },
    { id: "vin002", nome: "Vinho Tinto Merlot", descricao: "Vinho tinto macio e aveludado, com notas de ameixa e cereja.", preco: 139.39, categoria: "CARTA DE VINHOS" },
    { id: "vin003", nome: "Vinho Tinto Malbec", descricao: "Vinho tinto argentino intenso, com notas de frutas maduras e especiarias.", preco: 181.26, categoria: "CARTA DE VINHOS" },
    { id: "vin004", nome: "Vinho Branco Chardonnay", descricao: "Vinho branco encorpado, com notas de frutas amarelas e leve toque amanteigado.", preco: 137.81, categoria: "CARTA DE VINHOS" },
    { id: "vin005", nome: "Vinho Branco Sauvignon Blanc", descricao: "Vinho branco leve e ácido, com notas cítricas e herbáceas.", preco: 45.1, categoria: "CARTA DE VINHOS" },
    { id: "vin006", nome: "Vinho Rosé", descricao: "Vinho rosé fresco e frutado, ideal para dias quentes.", preco: 101.73, categoria: "CARTA DE VINHOS" },
    { id: "vin007", nome: "Espumante Brut", descricao: "Espumante seco e elegante, com borbulhas finas e persistentes.", preco: 48.41, categoria: "CARTA DE VINHOS" },
    { id: "vin008", nome: "Espumante Moscatel", descricao: "Espumante suave e adocicado, com aroma floral marcante.", preco: 207.59, categoria: "CARTA DE VINHOS" },
    { id: "vin009", nome: "Vinho Tinto Pinot Noir", descricao: "Vinho tinto leve e elegante, com notas de frutas vermelhas.", preco: 198.78, categoria: "CARTA DE VINHOS" },
    { id: "vin010", nome: "Vinho Tinto Syrah", descricao: "Vinho tinto encorpado, com notas de pimenta preta e frutas escuras.", preco: 190.54, categoria: "CARTA DE VINHOS" },
    { id: "vin011", nome: "Vinho Branco Riesling", descricao: "Vinho branco aromático, com acidez marcante e notas de frutas cítricas.", preco: 98.81, categoria: "CARTA DE VINHOS" },
    { id: "vin012", nome: "Vinho Tinto Tempranillo", descricao: "Vinho tinto espanhol equilibrado, com notas de baunilha e frutas maduras.", preco: 55.14, categoria: "CARTA DE VINHOS" },
    { id: "vin013", nome: "Vinho do Porto", descricao: "Vinho fortificado português, doce e encorpado, ideal para sobremesas.", preco: 198.65, categoria: "CARTA DE VINHOS" },
    { id: "vin014", nome: "Vinho Tinto Reserva", descricao: "Vinho tinto envelhecido em carvalho, complexo e encorpado.", preco: 210.72, categoria: "CARTA DE VINHOS" },
    { id: "vin015", nome: "Vinho Branco Verdejo", descricao: "Vinho branco espanhol fresco, com notas herbáceas e cítricas.", preco: 59.99, categoria: "CARTA DE VINHOS" },
    { id: "vin016", nome: "Vinho Tinto Cabernet Franc", descricao: "Vinho tinto elegante, com notas de pimentão verde e frutas vermelhas.", preco: 130.05, categoria: "CARTA DE VINHOS" },
    { id: "vin017", nome: "Espumante Rosé", descricao: "Espumante rosé frutado, com borbulhas delicadas e final refrescante.", preco: 57.11, categoria: "CARTA DE VINHOS" },
    { id: "vin018", nome: "Vinho Branco Moscato", descricao: "Vinho branco suave e frisante, com aroma floral e adocicado.", preco: 178.11, categoria: "CARTA DE VINHOS" },
    { id: "vin019", nome: "Vinho Tinto Carménère", descricao: "Vinho tinto chileno macio, com notas de frutas vermelhas e especiarias.", preco: 179.02, categoria: "CARTA DE VINHOS" },
    { id: "vin020", nome: "Vinho Branco Gewürztraminer", descricao: "Vinho branco aromático, com notas de lichia e flores brancas.", preco: 67.47, categoria: "CARTA DE VINHOS" },
    { id: "vin021", nome: "Vinho Tinto Sangiovese", descricao: "Vinho tinto italiano vibrante, com acidez marcante e notas de cereja.", preco: 128.17, categoria: "CARTA DE VINHOS" },
    { id: "vin022", nome: "Vinho Branco Pinot Grigio", descricao: "Vinho branco leve e refrescante, com notas cítricas sutis.", preco: 141.22, categoria: "CARTA DE VINHOS" },
    { id: "vin023", nome: "Vinho Tinto Zinfandel", descricao: "Vinho tinto californiano encorpado, com notas de frutas maduras e especiarias.", preco: 91.38, categoria: "CARTA DE VINHOS" },
    { id: "vin024", nome: "Vinho Tinto Corte Bordalês", descricao: "Blend de uvas tintas ao estilo bordalês, equilibrado e encorpado.", preco: 197.68, categoria: "CARTA DE VINHOS" },
    { id: "vin025", nome: "Vinho Branco Seco Nacional", descricao: "Vinho branco nacional seco, leve e de fácil harmonização.", preco: 119.05, categoria: "CARTA DE VINHOS" },
    { id: "vin026", nome: "Vinho Tinto Suave Nacional", descricao: "Vinho tinto nacional suave, ideal para quem prefere vinhos mais doces.", preco: 82.06, categoria: "CARTA DE VINHOS" },
    { id: "vin027", nome: "Vinho Tinto Garrafeira", descricao: "Vinho tinto de guarda, envelhecido, com notas complexas de frutas secas.", preco: 139.38, categoria: "CARTA DE VINHOS" },
    { id: "vin028", nome: "Vinho Branco Chenin Blanc", descricao: "Vinho branco versátil, com acidez equilibrada e notas de maçã verde.", preco: 172.74, categoria: "CARTA DE VINHOS" },
    { id: "vin029", nome: "Vinho Tinto Petit Verdot", descricao: "Vinho tinto encorpado, com taninos firmes e notas de frutas escuras.", preco: 80.2, categoria: "CARTA DE VINHOS" },
    { id: "vin030", nome: "Espumante Prosecco", descricao: "Espumante italiano leve e frutado, com borbulhas suaves.", preco: 99.55, categoria: "CARTA DE VINHOS" },
];

// Exporta os produtos para uso em outros arquivos (caso use módulos ES6)
// export default produtos;

// Lista das categorias, na ordem em que devem aparecer no menu
const categorias = [
    "ENTRADAS",
    "PRATO PRINCIPAL",
    "SOBREMESAS",
    "BEBIDAS",
    "CARTA DE VINHOS"
];